### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by szhllyyl** [yuedajiong/super-ai-vision-stereo-world-generate-triposr#9]
请教大佬，我看训练代码里，数据集指向了lion下的文件夹
`dataset_train = SuperVisionDataset(is_train=is_train, data_path='./data/image/resin/lion/images_split/train/', image_size=image_size)`
如果一份数据集合中多种样本，应该怎么设置呢

**Comment by yuedajiong** [comment]
如果做实验，你找几个立体模型，然后render不同角度和距离，得到一组图片，放这个目录就好。 或者指向你的目录。  做法参考nerf, gs的各种项目，都有类似的。

**Comment by yuedajiong** [comment]
我这里有个data.zip你可以先实验。

**Comment by szhllyyl** [comment]
> 如果做实验，你找几个立体模型，然后render不同角度和距离，得到一组图片，放这个目录就好。 或者指向你的目录。 做法参考nerf, gs的各种项目，都有类似的。
好的，感谢！新手尝试下

**Comment by szhllyyl** [comment]
> 如果做实验，你找几个立体模型，然后render不同角度和距离，得到一组图片，放这个目录就好。 或者指向你的目录。 做法参考nerf, gs的各种项目，都有类似的。

好的，感谢！新手尝试下
